# Generated by Django 3.2.2 on 2021-05-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20210513_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
