# Generated by Django 3.2.2 on 2021-05-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_story_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='google_maps_api_key',
            field=models.CharField(default='', max_length=255, verbose_name='Google Maps API Key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('NAVBAR_BRAND', 'Navbar brand image'), ('BOTTOM_NAVBAR_BRAND', 'Bottom navbar brand image'), ('HEADER_BACKGROUND', 'Header background image'), ('ABOUT_HAND_FARMING', 'About hand farming image'), ('GO_TO_OUR_YOUTUBE_CHANNEL_ICON', 'Go to our youtube channel icon'), ('GET_IT_ON_GOOGLE_PLAY', 'Get it on Google Play image'), ('DOWNLOAD_ON_THE_APP_STORE', 'Download on the App Store image'), ('FACEBOOK_SOCIAL_MEDIA_ICON', 'Facebook social media icon'), ('INSTAGRAM_SOCIAL_MEDIA_ICON', 'Instagram social media icon'), ('YOUTUBE_SOCIAL_MEDIA_ICON', 'Youtube social media icon')], max_length=255, unique=True, verbose_name='Type'),
        ),
    ]
