# Generated by Django 3.2.2 on 2021-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20210517_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='youtube_video_code',
            field=models.CharField(blank=True, help_text='Example: URL - https://www.youtube.com/watch?v=19bbXiGbfdk then video code is - 19bbXiGbfdk', max_length=255, null=True, verbose_name='Youtube video code'),
        ),
        migrations.AlterField(
            model_name='text',
            name='type',
            field=models.CharField(choices=[('NAVBAR_ABOUT_US', 'Navbar about us'), ('NAVBAR_OUR_IDEA', 'Navbar our idea'), ('NAVBAR_REVIEWS', 'Navbar reviews'), ('NAVBAR_NEWS', 'Navbar news'), ('NAVBAR_CONTACTS', 'Navbar contacts'), ('LANG_SELECTOR_UK_TEXT', 'Language selector ukrainian text'), ('LANG_SELECTOR_RU_TEXT', 'Language selector russian text'), ('LANG_SELECTOR_EN_TEXT', 'Language selector english text'), ('PAGE_MAIN_TITLE', 'Page main title'), ('PAGE_MAIN_SUBTITLE', 'Page main subtitle'), ('GO_TO_STORE_BUTTON_TEXT', 'Go to store button text'), ('YOUTUBE_TITLE', 'Youtube title'), ('YOUTUBE_CHANNEL_NAME', 'Youtube channel name'), ('QUESTIONS_SECTION_TITLE', 'Questions section title'), ('STORIES_SECTION_TITLE', 'Stories section title'), ('STORY_READ_MORE_BUTTON_TEXT', 'Story read more button text'), ('NEWS_SECTION_TITLE', 'News section title'), ('READ_MORE_NEWS_BUTTON_TEXT', 'Read more news button text'), ('CONTACTS_SECTION_TITLE', 'Contacts section title'), ('CONTACTS_ADDRESS_TEXT', 'Contacts address text'), ('CONTACTS_ADDRESS', 'Contacts address'), ('CONTACTS_PHONE_NUMBER_TEXT', 'Contacts phone number text'), ('CONTACTS_PHONE_NUMBER', 'Contacts phone number'), ('CONTACTS_EMAIL_TEXT', 'Contacts email text'), ('CONTACTS_EMAIL', 'Contacts email'), ('FEEDBACK_SECTION_TITLE', 'Feedback section title'), ('FEEDBACK_SECTION_SUBTITLE', 'Feedback section subtitle'), ('FEEDBACK_FORM_NAME_PLACEHOLDER', 'Feedback form name placeholder'), ('FEEDBACK_FORM_PHONE_NUMBER_PLACEHOLDER', 'Feedback form phone number placeholder'), ('FEEDBACK_FORM_EMAIL_PLACEHOLDER', 'Feedback form email placeholder'), ('FEEDBACK_FORM_MESSAGE_PLACEHOLDER', 'Feedback form message placeholder'), ('FEEDBACK_FORM_TERMS_TEXT', 'Feedback form terms text'), ('FEEDBACK_FORM_SUBMIT_BUTTON_TEXT', 'Feedback form submit button text'), ('SHARE_NEWS', 'Share news'), ('READ_OTHER_NEWS', 'Read other news'), ('COPY_NEWS_LINK', 'Copy news link')], max_length=255, unique=True, verbose_name='Type'),
        ),
    ]
