# Generated by Django 3.2.2 on 2021-05-18 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20210518_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Received at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='youtube_video_code',
            field=models.CharField(blank=True, help_text='Example: URL - https://www.youtube.com/watch?v=19bbXiGbfdk then video code is - 19bbXiGbfdk<br>Leave blank and video code will be detected automatically<br>If after saving this field still empty - fill it manually', max_length=255, null=True, verbose_name='Youtube video code'),
        ),
    ]
