# Generated by Django 3.2.2 on 2021-05-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_text_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('HAND_FARMING_APP_ON_GOOGLE_PLAY', 'Download Hand Farming app on Google Play'), ('HAND_FARMING_APP_ON_APP_STORE', 'Download Hand Farming app on App Store'), ('HAND_FARMING_SHOP', 'Hand Farming shop'), ('QUESTIONS_SECTION_DEFAULT_VIDEO_URL', 'Questions section default video URL')], max_length=255, unique=True, verbose_name='Type'),
        ),
    ]
