# Generated by Django 3.2.2 on 2021-05-13 13:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news', verbose_name='Image')),
                ('display_date', models.DateField(verbose_name='Display date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('short_description', models.CharField(max_length=255, verbose_name='Short description')),
                ('short_description_uk', models.CharField(max_length=255, null=True, verbose_name='Short description')),
                ('short_description_en', models.CharField(max_length=255, null=True, verbose_name='Short description')),
                ('short_description_ru', models.CharField(max_length=255, null=True, verbose_name='Short description')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text')),
                ('text_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text')),
                ('show', models.BooleanField(default=False, verbose_name='Show')),
                ('views_count', models.IntegerField(verbose_name='Views count')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
