# Generated by Django 3.2.2 on 2021-05-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Views count'),
        ),
    ]
