

class Texts:
    NAVBAR_ABOUT_US = 'NAVBAR_ABOUT_US'
    NAVBAR_OUR_IDEA = 'NAVBAR_OUR_IDEA'
    NAVBAR_REVIEWS = 'NAVBAR_REVIEWS'
    NAVBAR_NEWS = 'NAVBAR_NEWS'
    NAVBAR_CONTACTS = 'NAVBAR_CONTACTS'

    LANG_SELECTOR_UK_TEXT = 'LANG_SELECTOR_UK_TEXT'
    LANG_SELECTOR_RU_TEXT = 'LANG_SELECTOR_RU_TEXT'
    LANG_SELECTOR_EN_TEXT = 'LANG_SELECTOR_EN_TEXT'

    PAGE_MAIN_TITLE = 'PAGE_MAIN_TITLE'
    PAGE_MAIN_SUBTITLE = 'PAGE_MAIN_SUBTITLE'
    GO_TO_STORE_BUTTON_TEXT = 'GO_TO_STORE_BUTTON_TEXT'
    YOUTUBE_TITLE = 'YOUTUBE_TITLE'
    YOUTUBE_CHANNEL_NAME = 'YOUTUBE_CHANNEL_NAME'

    ABOUT_HAND_FARMING_TITLE = 'ABOUT_HAND_FARMING_TITLE'
    ABOUT_HAND_FARMING_SUBTITLE = 'ABOUT_HAND_FARMING_SUBTITLE'
    ABOUT_HAND_FARMING_TEXT = 'ABOUT_HAND_FARMING_TEXT'

    QUESTIONS_SECTION_TITLE = 'QUESTIONS_SECTION_TITLE'

    STORIES_SECTION_TITLE = 'STORIES_SECTION_TITLE'
    STORY_READ_MORE_BUTTON_TEXT = 'STORY_READ_MORE_BUTTON_TEXT'

    NEWS_SECTION_TITLE = 'NEWS_SECTION_TITLE'
    READ_MORE_NEWS_BUTTON_TEXT = 'READ_MORE_NEWS_BUTTON_TEXT'

    CONTACTS_SECTION_TITLE = 'CONTACTS_SECTION_TITLE'
    CONTACTS_ADDRESS_TEXT = 'CONTACTS_ADDRESS_TEXT'
    CONTACTS_ADDRESS = 'CONTACTS_ADDRESS'
    CONTACTS_PHONE_NUMBER_TEXT = 'CONTACTS_PHONE_NUMBER_TEXT'
    CONTACTS_PHONE_NUMBER = 'CONTACTS_PHONE_NUMBER'
    CONTACTS_EMAIL_TEXT = 'CONTACTS_EMAIL_TEXT'
    CONTACTS_EMAIL = 'CONTACTS_EMAIL'

    FEEDBACK_SECTION_TITLE = 'FEEDBACK_SECTION_TITLE'
    FEEDBACK_SECTION_SUBTITLE = 'FEEDBACK_SECTION_SUBTITLE'

    FEEDBACK_FORM_NAME_PLACEHOLDER = 'FEEDBACK_FORM_NAME_PLACEHOLDER'
    FEEDBACK_FORM_PHONE_NUMBER_PLACEHOLDER = 'FEEDBACK_FORM_PHONE_NUMBER_PLACEHOLDER'
    FEEDBACK_FORM_EMAIL_PLACEHOLDER = 'FEEDBACK_FORM_EMAIL_PLACEHOLDER'
    FEEDBACK_FORM_MESSAGE_PLACEHOLDER = 'FEEDBACK_FORM_MESSAGE_PLACEHOLDER'
    FEEDBACK_FORM_TERMS_TEXT = 'FEEDBACK_FORM_TERMS_TEXT'
    FEEDBACK_FORM_SUBMIT_BUTTON_TEXT = 'FEEDBACK_FORM_SUBMIT_BUTTON_TEXT'
    FEEDBACK_FORM_SUCCESS_MESSAGE = 'FEEDBACK_FORM_SUCCESS_MESSAGE'

    SHARE_NEWS = 'SHARE_NEWS'
    READ_OTHER_NEWS = 'READ_OTHER_NEWS'
    COPY_NEWS_LINK = 'COPY_NEWS_LINK'


class Images:
    NAVBAR_BRAND = 'NAVBAR_BRAND'
    BOTTOM_NAVBAR_BRAND = 'BOTTOM_NAVBAR_BRAND'
    HEADER_BACKGROUND = 'HEADER_BACKGROUND'
    ABOUT_HAND_FARMING = 'ABOUT_HAND_FARMING'
    GO_TO_OUR_YOUTUBE_CHANNEL_ICON = 'GO_TO_OUR_YOUTUBE_CHANNEL_ICON'
    GET_IT_ON_GOOGLE_PLAY = 'GET_IT_ON_GOOGLE_PLAY'
    DOWNLOAD_ON_THE_APP_STORE = 'DOWNLOAD_ON_THE_APP_STORE'
    FACEBOOK_SOCIAL_MEDIA_ICON = 'FACEBOOK_SOCIAL_MEDIA_ICON'
    INSTAGRAM_SOCIAL_MEDIA_ICON = 'INSTAGRAM_SOCIAL_MEDIA_ICON'
    YOUTUBE_SOCIAL_MEDIA_ICON = 'YOUTUBE_SOCIAL_MEDIA_ICON'
    SHARE_NEWS_ON_FACEBOOK = 'SHARE_NEWS_ON_FACEBOOK'


class Links:
    FACEBOOK = 'FACEBOOK'
    INSTAGRAM = 'INSTAGRAM'
    YOUTUBE = 'YOUTUBE'
    HAND_FARMING_APP_ON_GOOGLE_PLAY = 'HAND_FARMING_APP_ON_GOOGLE_PLAY'
    HAND_FARMING_APP_ON_APP_STORE = 'HAND_FARMING_APP_ON_APP_STORE'
    HAND_FARMING_SHOP = 'HAND_FARMING_SHOP'
    QUESTIONS_SECTION_DEFAULT_VIDEO_URL = 'QUESTIONS_SECTION_DEFAULT_VIDEO_URL'
